AWSTemplateFormatVersion: 2010-09-09
Description: A persistent data volume for adhoc instances

Parameters:
  InstanceName:
    Description: An unique name for the adhoc instance
    Type: String
    MinLength: 1
    MaxLength: 32

  VolumeSize:
    Description: The size of the volume to create (in GiBs)
    Type: Number
    Default: 5

Resources:
  PersistentDataVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !Sub '${AWS::Region}a'
      Encrypted: true
      Size: !Ref VolumeSize
      Tags:
        - { Key: Name, Value: !Sub '${AWS::StackName}-volume' }
      VolumeType: gp2

Outputs:
  PersistentDataVolume:
    Description: The ID of the persistent data volume
    Value: !Ref PersistentDataVolume
    Export:
      Name: !Sub 'adhoc-instance-${InstanceName}-volume'
