AWSTemplateFormatVersion: 2010-09-09
Description: An instance for adhoc work

Parameters:
  InstanceName:
    Description: An unique name for the adhoc instance
    Type: String
    MinLength: 1
    MaxLength: 32

  SSHKeyName:
    Description: Name of an existing EC2 SSH key to give the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: sjakthol

  SSHInboundCidr:
    Description: The CIDR from which SSH access should be allowed from
    Type: String
    Default: '0.0.0.0/0'
    AllowedPattern : "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription : 'must be a valid CIDR range of the form x.x.x.x/x.'

Mappings:
  Ami:
    eu-west-1:
      Ubuntu1604: ami-0181f8d9b6f098ec4
      Ubuntu1804: ami-0d137679f8243e9f8

Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Allow SSH access to host
      GroupName: !Sub ${AWS::StackName}-sg
      VpcId: !ImportValue infra-vpc-VpcId
      SecurityGroupIngress:
        - { IpProtocol: tcp, FromPort: 22, ToPort: 22, CidrIp: !Ref SSHInboundCidr, Description: "SSH Access" }
      Tags:
        - { Key: Name, Value: !Sub '${AWS::StackName}-sg' }

  Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      RoleName: !Sub ${AWS::StackName}-role
      Policies:
      - PolicyName: Ec2InstanceRole
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Sid: PlaceholderPolicy
            Effect: Allow
            Action:
              - ec2:DescribeInsances
              - kinesis:PutRecord
              - kinesis:PutRecords
            Resource: '*'

  RoleProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref Role
      InstanceProfileName: !Sub '${AWS::StackName}-profile'

  LaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-template
      LaunchTemplateData:
        EbsOptimized: true
        IamInstanceProfile:
          Arn: !GetAtt RoleProfile.Arn
        ImageId: !FindInMap [Ami, !Ref 'AWS::Region', Ubuntu1804]
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            SpotInstanceType: one-time
        InstanceType: m5.large
        KeyName: !Ref SSHKeyName
        SecurityGroupIds:
          - !Ref SecurityGroup
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - { Key: Name, Value: !Sub '${AWS::StackName}' }
          - ResourceType: volume
            Tags:
              - { Key: Name, Value: !Sub '${AWS::StackName}-volume' }
        UserData:
          Fn::Base64: !Sub |
            #cloud-config
            repo_update: true
            repo_upgrade: all
            fs_setup:
              - device: /dev/nvme1n1
                filesystem: ext4
                label: home
            mounts:
              - [/dev/nvme1n1, /data, auto, "defaults,nofail,discard", "0", "0"]

  Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      SubnetId: !ImportValue infra-vpc-sn-adhoc-a

  VolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      Device: /dev/xvdh
      InstanceId: !Ref Instance
      VolumeId:
        Fn::ImportValue: !Sub 'adhoc-instance-${InstanceName}-volume'
